version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
  client:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  data:
  logs: